### ISSUE TITLE
I have to select a theme every time

### ISSUE THREAD

**Issue by brudajj** [Godiesc/gx-theme-styles#1]
I have to select a theme every time for it to take affect. When I open the browser it tries loading the last used theme for a second and then it immediately goes back to normal. The only way I can use a theme is by manually selecting it each time I boot up Firefox which gets really annoying after a while.

**Comment by Godiesc** [comment]
hi,
thanks for the report, the information right now is that its a Firefox bug, this is a [post where a Firefox employee answer](https://www.reddit.com/r/firefox/comments/1ggdulb/my_firefox_colors_theme_has_been_removing_itself/). It refers to this bug in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1928082

I tested and if you have selected the 'system theme - automatic' in `about:addons` page the bug persist but if you choose other, restart the browser, then the theme from the extension will apply without problems, let me know if that works.

**Comment by brudajj** [comment]
yup it works
